### ISSUE TITLE
Sporadic errors when updating shop threads

### ISSUE THREAD

**Issue by tomholz** [tomholz/acquisition#5]
In v0.9.9, I added extra checks when updating shop threads to catch errors that v0.9.7 was silently missing. It looks like GGG has updated the forum website so that errors can show up differently now. Now there is sometimes an error updating shop threads. After some debugging, it looks like the error message is "Security token has expired. Please submit the form again."

v0.9.9 correctly detects this error, but doesn't do anything about it yet.

**Comment by Jozen2023** [comment]
Been using beta 3 version for a couple days, got only one error once after installing. Unfortunately didnt capture it (not a code or something small, but a huge chunk of red text in log area) and couldnt replicate it after that. 
Its working fine so far, updating my 40 ish stashes manually after unloading and pricing half hour worth of items/things or so and updating shop thread without issues.

**Comment by Jozen2023** [comment]
Since current league is approaching to end and population/interest of players is drastically dwindling it might be worth to open a topic in issues with a direct link and and explanation to this branch, and also a topic in redit with POE Aquisition and several other keywords, so ppl who are searching to find it easily. That can lead to more testers and feedback, and hopefully to a stable release version.
Good luck!

**Comment by tomholz** [comment]
@Jozen2023, the only error I've seen with beta 3 was a shop forum thread update error, which should be addressed by https://github.com/tomholz/acquisition/releases/tag/v0.9.9-beta.4. At this point, I'm not planing any new features or changes before releasing v0.9.9.

I'm traveling this week, so it won't happen until I get back because I want to be responsive when people report bugs or ask questions on the reddit announcement thread.

(There's a silver lining, however, because my travel laptop is a MacBook Air and I'm close to a working macOS port.)

**Comment by tomholz** [comment]
I'm closing this issue for now since the problem seems to be resolved with beta 4.
